export { MapConfigEncryptionMigration, MAP_CONFIG_MIGRATION_DONE } from './migrate-mapconfig-encryption';
export { PayConfigEncryptionMigration, PAY_CONFIG_MIGRATION_DONE } from './migrate-payconfig-encryption';
export { TenantMemberColumnMigration } from './migrate-tenant-member-column';
export { AddTenantMemberRedeemProfiles } from './add-tenant-member-redeem-profiles';
export { ChannelCustomColumnMigration } from './migrate-channel-custom-column';
export { ShippingContactFlagMigration } from './migrate-shipping-contact-flags';
export { StockTableMigration, ChannelInventoryModeColumnMigration } from './migrate-stock-tables';
export { CollectionIconMigration } from './migrate-collection-icon';
export { ReservationExpiresAtMigration } from './migrate-reservation-expires-at';
export { ReservationTtlColumnMigration } from './migrate-reservation-ttl-column';
export { PickBatchHandoverColumnMigration } from './migrate-pick-batch-handover-columns';
export { StocktakePostedDocIndexMigration } from './migrate-stocktake-posted-doc-index';
export { HotelOrderLineColumnMigration } from './migrate-hotel-order-line-columns';
