"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.chinaProvinces = void 0;
exports.chinaProvinces = [
    { code: 'CN-BJ', name: '北京市' },
    { code: 'CN-TJ', name: '天津市' },
    { code: 'CN-HE', name: '河北省' },
    { code: 'CN-SX', name: '山西省' },
    { code: 'CN-NM', name: '内蒙古自治区' },
    { code: 'CN-LN', name: '辽宁省' },
    { code: 'CN-JL', name: '吉林省' },
    { code: 'CN-HL', name: '黑龙江省' },
    { code: 'CN-SH', name: '上海市' },
    { code: 'CN-JS', name: '江苏省' },
    { code: 'CN-ZJ', name: '浙江省' },
    { code: 'CN-AH', name: '安徽省' },
    { code: 'CN-FJ', name: '福建省' },
    { code: 'CN-JX', name: '江西省' },
    { code: 'CN-SD', name: '山东省' },
    { code: 'CN-HA', name: '河南省' },
    { code: 'CN-HB', name: '湖北省' },
    { code: 'CN-HN', name: '湖南省' },
    { code: 'CN-GD', name: '广东省' },
    { code: 'CN-GX', name: '广西壮族自治区' },
    { code: 'CN-HI', name: '海南省' },
    { code: 'CN-CQ', name: '重庆市' },
    { code: 'CN-SC', name: '四川省' },
    { code: 'CN-GZ', name: '贵州省' },
    { code: 'CN-YN', name: '云南省' },
    { code: 'CN-XZ', name: '西藏自治区' },
    { code: 'CN-SN', name: '陕西省' },
    { code: 'CN-GS', name: '甘肃省' },
    { code: 'CN-QH', name: '青海省' },
    { code: 'CN-NX', name: '宁夏回族自治区' },
    { code: 'CN-XJ', name: '新疆维吾尔自治区' },
    { code: 'CN-TW', name: '台湾省' },
    { code: 'CN-HK', name: '香港特别行政区' },
    { code: 'CN-MO', name: '澳门特别行政区' },
];
//# sourceMappingURL=china.js.map