-- 补建 order_stock_ledger 供销存账本中间表（生产库缺失）
-- 属 schema 变更，幂等（IF NOT EXISTS）
SELECT '-- create order_stock_ledger' AS info;

CREATE TABLE IF NOT EXISTS order_stock_ledger (
    "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "createdAt"    timestamp NOT NULL DEFAULT now(),
    "updatedAt"    timestamp NOT NULL DEFAULT now(),
    "version"      integer NOT NULL DEFAULT 0,
    "code"         character varying NOT NULL,
    "productVariantId" integer NOT NULL,
    "stockLocationId" integer NOT NULL,
    "bizType"      character varying NOT NULL,
    "bizCode"      character varying,
    "orderLineId"  integer,
    "direction"    character varying NOT NULL,
    "quantity"     integer NOT NULL,
    "beforeOnHand" integer,
    "afterOnHand"  integer,
    "otherLocationId" integer,
    "reason"       character varying
);

CREATE INDEX IF NOT EXISTS "IDX_order_stock_ledger_bizcode" ON order_stock_ledger ("bizCode");
CREATE INDEX IF NOT EXISTS "IDX_order_stock_ledger_variant" ON order_stock_ledger ("productVariantId", "stockLocationId");

-- channel 多对多关联表（对应实体 @ManyToMany Channel + @JoinTable）
CREATE TABLE IF NOT EXISTS order_stock_ledger_channels_channel (
    "orderStockLedgerId" integer NOT NULL,
    "channelId" integer NOT NULL,
    CONSTRAINT "UQ_order_stock_ledger_channels" UNIQUE ("orderStockLedgerId", "channelId")
);

SELECT '-- verify' AS info;
SELECT table_name FROM information_schema.tables
WHERE table_schema='public'
  AND table_name IN ('order_stock_ledger','order_stock_ledger_channels_channel')
ORDER BY table_name;