import { Channel, CustomFields, LanguageCode } from '@vendure/core';
import { MARKETPLACE_STATUS_PENDING, SALE_SOURCE_OWN } from './constants';

export const marketplaceCustomFields: CustomFields = {
    Product: [
        {
            name: 'listedInMarketplace',
            type: 'boolean',
            defaultValue: false,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '是否在 marketplace 展示' }],
        },
        {
            name: 'marketplaceStatus',
            type: 'string',
            defaultValue: MARKETPLACE_STATUS_PENDING,
            label: [{ languageCode: LanguageCode.zh_Hans, value: 'marketplace 审批状态' }],
        },
        {
            name: 'rejectReason',
            type: 'string',
            nullable: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '驳回原因' }],
        },
        {
            name: 'merchantRef',
            type: 'relation',
            entity: Channel,
            nullable: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '商家归属' }],
        },
        {
            name: 'barcode',
            type: 'string',
            nullable: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '统一条形码' }],
        },
        {
            name: 'internalCode',
            type: 'string',
            nullable: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '内部编码' }],
        },
        {
            name: 'marketingTags',
            type: 'text',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '营销标签（JSON 数组）' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '存 JSON 字符串数组，如 ["new","hot"]；仅存 code，前端按语言映射 label' }],
        },
        {
            name: 'sellingPoint',
            type: 'localeString',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '卖点/促销语' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '多语言卖点，本期仅维护 zh_Hans，其余语言槽位预留' }],
        },
        {
            name: 'tenantCategoryRef',
            type: 'string',
            nullable: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '商品所属租户分类名（归位依据）' }],
        },
        {
            name: 'platformCategoryId',
            type: 'string',
            nullable: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '已归位的平台分类' }],
        },
        {
            name: 'needsCategorization',
            type: 'boolean',
            defaultValue: false,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '待归类' }],
        },
        {
            name: 'videoAssetId',
            type: 'string',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '商品主视频' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '存视频 asset id，C 端松取 source 渲染播放' }],
        },
        {
            name: 'promos',
            type: 'text',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '促销方案（JSON 数组）' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '存 JSON 字符串数组，如 ["freeShip99","refund7"]；code 对应频道方案库 promoSchemes' }],
        },
        {
            name: 'services',
            type: 'text',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '服务保障（JSON 数组）' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '存 JSON 字符串数组，如 ["genuine","fastShip"]；code 对应频道方案库 serviceSchemes' }],
        },
        {
            name: 'salesCount',
            type: 'int',
            defaultValue: 0,
            public: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '展示销量' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '由 ProductStatsService 重算写回：realSalesCount + bonusSales；C 端只读此字段' }],
        },
        {
            name: 'realSalesCount',
            type: 'int',
            defaultValue: 0,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '真实销量（订单聚合）' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: 'Σ orderLine.quantity，仅计已支付及之后状态的订单；全渠道合计；每日 03:05 重算' }],
        },
        {
            name: 'bonusSales',
            type: 'int',
            defaultValue: 0,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '展示基数（运营手填）' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '叠加在真实销量之上的展示基数；改动后展示值即时重算' }],
        },
        {
            name: 'pointsReward',
            type: 'int',
            nullable: true,
            public: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '可得积分（展示）' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '由 ProductStatsService 重算写回：pointsRewardOverride ?? 最低变体不含税价' }],
        },
        {
            name: 'pointsRewardOverride',
            type: 'int',
            nullable: true,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '可得积分覆盖值' }],
            description: [{ languageCode: LanguageCode.zh_Hans, value: '填了则直接作为展示积分，不再按价格派生' }],
        },
    ],
    Order: [
        {
            name: 'saleSource',
            type: 'string',
            defaultValue: SALE_SOURCE_OWN,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '销售来源' }],
        },
    ],
    Channel: [
        {
            name: 'settlementBasis',
            type: 'string',
            defaultValue: 'paid',
            label: [{ languageCode: LanguageCode.zh_Hans, value: '对账口径' }],
        },
    ],
    Seller: [
        {
            name: 'marketplaceMerchant',
            type: 'boolean',
            defaultValue: false,
            label: [{ languageCode: LanguageCode.zh_Hans, value: '是否 marketplace 商家' }],
        },
    ],
};